#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket"
        # -S: Start, -n: Name, -a: App path, -p: Pidfile, -b: Background (optional if -d is used)
        start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesdsocket"
        # -K: Kill, -n: Name, -s: Signal (SIGTERM is default)
        start-stop-daemon -K -n aesdsocket
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0